### ISSUE TITLE
Question: does freeztp set priority of switches in stack

### ISSUE THREAD

**Issue by rssluca** [convergeone/freeztp#21]
Hello!

As per subject, if i set ztp set idarray STACK1 SERIAL1 SERIAL2 SERIAL3.

Thanks for your work!

Luca

**Comment by PackeTsar** [comment]
No it does not. And I'm not sure if you can do that with FreeZTP. I believe priority is set in enable mode, not in config mode, so I don't know if adding that config to the template will be interpreted properly by the switch.

An IDArray only allows you to match multiple real-id's to a keystore.

**Comment by rssluca** [comment]
Hi and thanks.

Yes I agree it can't be done like that, it needs to be done separately like here https://github.com/aradford123/ZTP-samples/blob/master/script/03-stack-ztd.py

For now will try to use freeztp to just upgrade the ios, gotta stage 100+ 3850s next week

I emptied both short and long templates for now.

Cheers,

Luca

**Comment by PackeTsar** [comment]
Yea you can still use FreeZTP to deploy most of your config. You just have to script the stack config to hit the switches separately.

I have a feature on the roadmap to be able to kick off a BASH command after the completion of a provisioning with the ability to templatize the command using values from the matched keystore. That would probably fully solve what you are trying to do. Just not there yet.
