### ISSUE TITLE
Persistent store error

### ISSUE THREAD

**Issue by rssluca** [convergeone/freeztp#22]
Hello,

I am getting this error when I try to show provisioning

2018-05-02 10:30:44:   persistent_store: ERROR: Error in reading from store file

2018-05-02 10:30:44:   persistent_store: ERROR: No JSON object could be decoded

I only changed DHCP scope, other than that cfg is default.

Cheers,
Luca

**Comment by rssluca** [comment]
I just did some more tests, it looks like this happens when i power cycle the pi (without proper shutdown)

`2018-05-03 12:40:00:   #########################################################

2018-05-03 12:40:00:   Starting the ZTP Service

● ztp.service - FreeZTP Service
   Loaded: loaded (/etc/systemd/system/ztp.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2018-05-03 12:39:24 UTC; 36s ago
 Main PID: 367 (bash)
   CGroup: /system.slice/ztp.service
           ├─367 /bin/bash -c cd /bin; python ztp run
           └─388 python ztp run

May 03 12:39:59 raspberrypi bash[367]:     fulldb = self._pull_full_db()  # Pull a full copy of the db
May 03 12:39:59 raspberrypi bash[367]:   File "ztp", line 2327, in _pull_full_db
May 03 12:39:59 raspberrypi bash[367]:     result = json.loads(rawdata)
May 03 12:39:59 raspberrypi bash[367]:   File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
May 03 12:39:59 raspberrypi bash[367]:     return _default_decoder.decode(s)
May 03 12:39:59 raspberrypi bash[367]:   File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
May 03 12:39:59 raspberrypi bash[367]:     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
May 03 12:39:59 raspberrypi bash[367]:   File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
May 03 12:39:59 raspberrypi bash[367]:     raise ValueError("No JSON object could be decoded")
May 03 12:39:59 raspberrypi bash[367]: ValueError: No JSON object could be decoded
2018-05-03 12:40:00:   #########################################################`

**Comment by PackeTsar** [comment]
Strange. Looks like something got corrupted in the db. Try deleting the db `rm /etc/ztp/pdb` and restart the service `ztp service restart`

**Comment by rssluca** [comment]
Done and all good, it does it every time the pi is not shutdown properly.

Also, new one after after provisioning first batch.

2018-05-03 14:41:01:   persistent_store: ERROR: Error in reading from store file

2018-05-03 14:41:01:   persistent_store: ERROR: Extra data: line 237 column 2 - line 249 column 2 (char 7879 - 8208)

2018-05-03 14:41:01:   persistent_store: ERROR: Error in reading from store file

2018-05-03 14:41:01:   persistent_store: ERROR: Extra data: line 237 column 2 - line 249 column 2 (char 7879 - 8208)

2018-05-03 14:41:01:   persistent_store: ERROR: Error in reading from store file

2018-05-03 14:41:01:   persistent_store: ERROR: Extra data: line 237 column 2 - line 249 column 2 (char 7879 - 8208)

Will do some more tshooting..

**Comment by PackeTsar** [comment]
Can you attach a sanitized copy of the pdb file here?

**Comment by PackeTsar** [comment]
And did the provisioning work OK?

**Comment by rssluca** [comment]
Already removed unfortunately. Will grab one if it happens again.

I added 6 switches then another 4 after 5 minutes.

The first batch did the upgrade, however, only 2 took the cfg, while the other did not (I am checking whether the hostname has changed to confirm the sw has been installed) the other 4 did not upgrade.

Will keep you posted.

**Comment by rssluca** [comment]
Done again, looks like json is malformed?

{
    "provisioning": {
        "1525359432.528907": {
            "IP Address": "192.168.10.20", 
            "MAC Address": "00:87:31:ca:29:c7", 
            "Matched Keystore": "DEFAULT_VALUES", 
            "Real IDs": {
                "WS-C2960_SERIAL_NUMBER": "", 
                "WS-C3850_SERIAL_NUMBER": "FOC2032U00K"
            }, 
            "Status": "Complete", 
            "Temp ID": "ZTP-2383D9C7CD", 
            "Timestamp": 1525359455.038549
        }, 
        "1525359443.993212": {
            "IP Address": "192.168.10.23", 
            "MAC Address": "00:87:31:b1:63:c7", 
            "Matched Keystore": "DEFAULT_VALUES", 
            "Real IDs": {
                "WS-C2960_SERIAL_NUMBER": "", 
                "WS-C3850_SERIAL_NUMBER": "FOC2031U0WE"
            }, 
            "Status": "Complete", 
            "Temp ID": "ZTP-2383D9CCCF", 
            "Timestamp": 1525359466.320576
        }, 
        "1525359449.332782": {
            "IP Address": "192.168.10.22", 
            "MAC Address": "d4:2c:44:39:00:c7", 
            "Matched Keystore": "DEFAULT_VALUES", 
            "Real IDs": {
                "WS-C2960_SERIAL_NUMBER": "", 
                "WS-C3850_SERIAL_NUMBER": "FCW2031C0RG"
            }, 
            "Status": "Complete", 
            "Temp ID": "ZTP-2383D9CEE5", 
            "Timestamp": 1525359472.009306
        }, 
        "1525359452.395822": {
            "IP Address": "192.168.10.21", 
            "MAC Address": "d4:2c:44:c8:87:c7", 
            "Matched Keystore": "DEFAULT_VALUES", 
            "Real IDs": {
                "WS-C2960_SERIAL_NUMBER": "", 
                "WS-C3850_SERIAL_NUMBER": "FOC2031U046"
            }, 
            "Status": "Complete", 
            "Temp ID": "ZTP-2383D9D017", 
            "Timestamp": 1525359473.914316
        }, 
        "1525361167.917669": {
            "IP Address": "192.168.10.27", 
            "MAC Address": "00:87:31:a1:44:c7", 
            "Matched Keystore": null, 
            "Real IDs": null, 
            "Status": "Incomplete", 
            "Temp ID": "ZTP-2383DC6E37", 
            "Timestamp": 1525361167.917669
        }
    }, 
    "tracking": {
        "1525358976.222407": {
            "active": false, 
            "bytessent": 512, 
            "filename": "freeztp_ios_upgrade", 
            "filesize": 49, 
            "ipaddr": "192.168.10.22", 
            "percent": 100.0, 
            "ports": {
                "1025": 1525358976.222236, 
                "1026": 1525358976.240579
            }, 
            "position": 512, 
            "rate": "0 bps", 
            "time": "2018-05-03 14:49:36"
        }, 
        "1525358977.917098": {
            "active": false, 
            "bytessent": 303772864, 
            "filename": "cat3k_caa-universalk9.SPA.03.06.06.E.152-2.E6.bin", 
            "filesize": 303772864, 
            "ipaddr": "192.168.10.22", 
            "percent": 100.0, 
            "ports": {
                "1027": 1525358977.916892, 
                "1028": 1525358979.892158, 
                "1029": 1525358981.914307, 
                "1030": 1525358986.786844
            }, 
            "position": 303772864, 
            "rate": "0 bps", 
            "time": "2018-05-03 14:49:37"
        }, 
        "1525359431.166033": {
            "active": false, 
            "bytessent": 512, 
            "filename": "network-confg", 
            "filesize": 72, 
            "ipaddr": "192.168.10.21", 
            "percent": 100.0, 
            "ports": {
                "1050": 1525359431.165873, 
                "1051": 1525359432.621823, 
                "1052": 1525359444.066506
            }, 
            "position": 512, 
            "rate": "0 bps", 
            "time": "2018-05-03 14:57:11"
        }, 
        "1525359453.074521": {
            "active": false, 
            "bytessent": 512, 
            "filename": "ZTP-2383D9C7CD-confg", 
            "filesize": 21, 
            "ipaddr": "192.168.10.20", 
            "percent": 100.0, 
            "ports": {
                "1055": 1525359453.07434, 
                "1056": 1525359455.059241
            }, 
            "position": 512, 
            "rate": "0 bps", 
            "time": "2018-05-03 14:57:33"
        }, 
        "1525359465.235071": {
            "active": false, 
            "bytessent": 512, 
            "filename": "ZTP-2383D9CCCF-confg", 
            "filesize": 21, 
            "ipaddr": "192.168.10.23", 
            "percent": 100.0, 
            "ports": {
                "1056": 1525359465.23468, 
                "1057": 1525359466.349708
            }, 
            "position": 512, 
            "rate": "0 bps", 
            "time": "2018-05-03 14:57:45"
        }, 
        "1525359470.99414": {
            "active": false, 
            "bytessent": 512, 
            "filename": "ZTP-2383D9CEE5-confg", 
            "filesize": 21, 
            "ipaddr": "192.168.10.22", 
            "percent": 100.0, 
            "ports": {
                "1056": 1525359470.993974, 
                "1057": 1525359472.027175
            }, 
            "position": 512, 
            "rate": "0 bps", 
            "time": "2018-05-03 14:57:50"
        }, 
        "1525359472.882405": {
            "active": false, 
            "bytessent": 512, 
            "filename": "ZTP-2383D9D017-confg", 
            "filesize": 21, 
            "ipaddr": "192.168.10.21", 
            "percent": 100.0, 
            "ports": {
                "1056": 1525359472.882289, 
                "1057": 1525359473.942229
            }, 
            "position": 512, 
            "rate": "0 bps", 
            "time": "2018-05-03 14:57:52"
        }, 
        "1525360702.790545": {
            "active": false, 
            "bytessent": 512, 
            "filename": "freeztp_ios_upgrade", 
            "filesize": 49, 
            "ipaddr": "192.168.10.30", 
            "percent": 100.0, 
            "ports": {
                "1025": 1525360702.790376, 
                "1026": 1525360702.809602
            }, 
            "position": 512, 
            "rate": "0 bps", 
            "time": "2018-05-03 15:18:22"
        }, 
        "1525360704.402945": {
            "active": false, 
            "bytessent": 303772864, 
            "filename": "cat3k_caa-universalk9.SPA.03.06.06.E.152-2.E6.bin", 
            "filesize": 303772864, 
            "ipaddr": "192.168.10.30", 
            "percent": 100.0, 
            "ports": {
                "1027": 1525360704.402734, 
                "1028": 1525360706.377339, 
                "1029": 1525360708.397652, 
                "1030": 1525360712.686495
            }, 
            "position": 303772864, 
            "rate": "0 bps", 
            "time": "2018-05-03 15:18:24"
        }, 
        "1525361167.89799": {
            "active": true, 
            "bytessent": 512, 
            "filename": "network-confg", 
            "filesize": 72, 
            "ipaddr": "192.168.10.24", 
            "percent": 100.0, 
            "ports": {
                "1050": 1525361167.897824, 
                "1051": 1525361168.010565
            }, 
            "position": 512, 
            "rate": "0 bps", 
            "time": "2018-05-03 15:26:07"
        }
    }
}esize": 72, 
            "ipaddr": "192.168.10.27", 
            "percent": 100.0, 
            "ports": {
                "1050": 1525361167.897824, 
                "1051": 1525361168.010565
            }, 
            "position": 512, 
            "rate": "0 bps", 
            "time": "2018-05-03 15:26:07"
        }
    }
}

**Comment by rssluca** [comment]
Ok, patched 8 together, 5 in json then same issue. It did push the new io to all of them though, just not all got the cfg. Json file attached.
[pdb.txt](https://github.com/PackeTsar/freeztp/files/1973155/pdb.txt)

**Comment by PackeTsar** [comment]
yea I can see towards the bottom where the JSON file got screwed up. So what happens when they don't get their configs? Is it because the ZTP server crashes in the middle of provisioning?

**Comment by rssluca** [comment]
Not sure! Will do some more testing tomorrow and keep you posted.

Luca

**Comment by derek-shnosh** [comment]
Ran into the same thing today, everything was working fine and started seeing the following when running `ztp show provisioning/dhcp leases/downloads`;

```
$ ztp show provisioning 
10:54:38 -- Unable to log to logfile /etc/ztp/ztp.log. Make sure FreeZTP is installed. Disabling logging to logfile
10:54:38 -- 2018-09-18 10:54:45:   persistent_store: ERROR: Error in reading from store file
10:54:38 -- 
10:54:38 -- 2018-09-18 10:54:45:   persistent_store: ERROR: Extra data: line 12871 column 5 - line 12872 column 2 (char 453228 - 453231)
10:54:38 -- 
10:54:38 -- 2018-09-18 10:54:45:   persistent_store: ERROR: Error in reading from store file
10:54:38 -- 
10:54:38 -- 2018-09-18 10:54:45:   persistent_store: ERROR: Extra data: line 12871 column 5 - line 12872 column 2 (char 453228 - 453231)
10:54:38 -- 
10:54:38 -- 2018-09-18 10:54:45:   persistent_store: ERROR: Error in reading from store file
10:54:38 -- 
10:54:38 -- 2018-09-18 10:54:45:   persistent_store: ERROR: Extra data: line 12871 column 5 - line 12872 column 2 (char 453228 - 453231)
```

I'm wondering if we hit some kind of line/size limit.

Anyways, resolved by backing up the pdb file and restarting ztp services.

```bash
mv /etc/ztp/pdb /etc/ztp/pdb.bak
ztp services restart
```

@PackeTsar, let me know if you want the pdb file for review.

**Comment by PackeTsar** [comment]
I have seen recurring reports of this issue. It may be related to how I am writing data to that file. Thinking that it may get corrupted due to multiple concurrent writes. I will look into this.

**Comment by PackeTsar** [comment]
Tracking this. Closing.
