### ISSUE TITLE
Specify an image file per hardware type

### ISSUE THREAD

**Issue by gbieli** [convergeone/freeztp#23]
I'd like to use FreeZTP to provision a 2960X and a 3850 in parallel with IOS Upgrades.
Is it possible to specify an image file per hardware type or per switch? I cannot figure out how to do that.

**Comment by PackeTsar** [comment]
This is not currently possible

**Comment by PackeTsar** [comment]
This is not possible because of how the autoinstall functionality works. AFAIK only one file can be specified.
