### ISSUE TITLE
Request // re-cache templates or keystores without 'service restart'

### ISSUE THREAD

**Issue by derek-shnosh** [convergeone/freeztp#34]
Template and keystore re-caching would be a welcome feature; more of a nice-to-have. This would allow templates or keystores (or both) to be re-cached without performing a `ztp service restart` which would interrupt any ongoing downloads.

More useful for keystores, so switch serial numbers can be added to CSVs as they're taken from inventory/unboxed/etc.

Not as necessary for templates, as any changes should be ironed out with test runs before provisioning begins; *but sometimes people are tired*, haha.

e.g.
`ztp cache (template <template> | templates)` #Recache a single template, or all templates.
`ztp cache (keystore <keystore> | keystores)` #Recache a single keystore, or all keystores
...
`ztp cache files` #Recache all templates and keystores.

**Comment by PackeTsar** [comment]
Added to enhancement requests. Closing this for now
