### ISSUE TITLE
dev1.1.0m // `Show Downloads` output for concurrent downloads of the same file

### ISSUE THREAD

**Issue by derek-shnosh** [convergeone/freeztp#35]
Concurrent downloads of the same file are being shown on one line of the `ztp show downloads (live)` output; the invidual line is just cycling through the IPs of all the switches that are downloading the same file on a *refresh/update*.

This seems to affect the downloads tracking for tar/bin downloads and possibly even the switches' requests for **network-confg** (if they happen simultaneously).

On our most recent batch of 2960X's, the switches were getting their tar file, extracting and installing it, reloading and then redownloading the tar file again; I'm assuming because the download wasn't tracked for all of the switches... that is if the `ztp show downloads` issue isn't purely cosmetic.

**Update:** According to the show downloads output, the last switch that downloaded the tar file had the IP 10.39.3.214 and it was handed a **Image_Download_Supressed** file after it reloaded. The other 15 switches started downloading the image tar file again.

![2018-10-02_10-50-23](https://user-images.githubusercontent.com/21090563/46366871-0981d180-c631-11e8-9c10-9fff5e3bab7f.gif)

**Comment by PackeTsar** [comment]
Added this to the requested enhancement list. Closing for now
