### ISSUE TITLE
dev1.1.0m // `Show downloads live` have a max line limit?

### ISSUE THREAD

**Issue by derek-shnosh** [convergeone/freeztp#36]
It seems that there may be an output limit preventing `ztp show downloads live` from displaying active downloads.

After clearing the downloads the live view works, but after some time and a number of downloads have completed, the live update stops and we're returned to the user prompt.

Unfortunately I wasn't watching when it exited so I don't know how many downloads it was tracking, but we currently have 55 downloads in the tracking table and if we enter the command it simply returns to the user prompt without showing any output.

Maybe having the `ztp show downloads live` option only display the last 15-20 downloads initiated/on-going would be ideal; the standard `ztp show downloads` command should still show everything (since the last clear).

**Comment by PackeTsar** [comment]
Tracking this in #46. Closing
