### ISSUE TITLE
External template not using complex JSON values

### ISSUE THREAD

**Issue by marcabomb** [convergeone/freeztp#38]
I have a stack of 2960-X switches that I am provisioning. They successfully download the code and grab the final config but the final config is missing the variables defined in the Keystore settings. I have included some of the log files below with my serial numbers replaced with placeholders and only part of the config. The hostname line in the config is one of the examples where the variable isn't merged in.

**Partial Log**
2019-03-07 15:25:48:   cfact.merge_final_config: Merging with values:
{
    "keystore_id": "placeholder-216",
    "settings": "{hostname: placeholder-216, ip_name_server: 10.5.180.29, wireless_interface_range: gi2/0/1-6,gi2/0/43-48,data_interface_range: gi1/0/1-48,gi2/0/7-42,ten1_0_1_uplink_switch_port: Te1/0/1,ten
1_0_2_uplink_switch_port: Te1/0/2, mgmt_ip: 10.51.183.216, mgmt_ip_mask: 255.255.252.0, default_gateway: 10.51.180.1, snmp_server_location: Placeholder \u2013 MDF 216 \u2013 Library Back Room}",
    "idarray_2": "B",
    "idarray_3": "C",
    "idarray_1": "A",
    "idarray": [
        "A",
        "B",
        "C",
        "D"
    ],
    "idarray_4": "D"
}
2019-03-07 15:25:48:   cfact.request: Returning the below config to TFTPy:
#########################
no service pad
service timestamps debug datetime msec localtime show-timezone
service timestamps log datetime msec localtime show-timezone
service password-encryption
service compress-config
!
hostname
!

**Here is part of the external template file to match. I tried {{ settings.hostname }} and {{ hostname }}.**
no service pad
service timestamps debug datetime msec localtime show-timezone
service timestamps log datetime msec localtime show-timezone
service password-encryption
service compress-config
!
hostname {{ hostname }}
!

**ZTP config**
ztp set keystore Placeholder-216 keystore_id Placeholder-216
ztp set keystore Placeholder-216 settings '{hostname: Placeholder-216, ip_name_server: 10.5.180.29, wireless_interface_range: gi2/0/1-6,gi2/0/43-48,data_interface_range: gi1/0/1-48,gi2/0/7-42,ten1_0_1_uplink_switch_port: Te1/0/1,ten1_0_2_uplink_switch_port: Te1/0/2, mgmt_ip: 10.51.183.216, mgmt_ip_mask: 255.255.252.0, default_gateway: 10.51.180.1, snmp_server_location: Placeholder – MDF 216 – Library Back Room}'
ztp set idarray Placeholder-216 A B C D
ztp set association id Placeholder-216 template BCPS-IDF
ztp set association id SERIAL100 template SHORT_TEMPLATE
ztp set default-keystore DEFAULT_VALUES
ztp set default-template LONG_TEMPLATE
ztp set imagefile c2960x-universalk9-mz.152-4.E6.bin
ztp set image-supression 5
ztp set delay-keystore 1000
ztp set external-template PLACEHOLDER-IDF file '/root/freeztp/bcps-idf-template.j2'

**Comment by PackeTsar** [comment]
It looks like your complex (JSON-based) values are malformed (missing quotes). I was able to get it working with the below config. You will need to use `settings.hostname` in the template for it to work.

To be honest, if you have this many variables and you have many keystores, you may just want to use a CSV-based external template and just use flat variables. It will probably make your life easier.


```
ztp set keystore Placeholder-216 settings '{"mgmt_ip_mask": "255.255.252.0", "wireless_interface_range": "gi2/0/1-6,gi2/0/43-48", "mgmt_ip": "10.51.183.216", "default_gateway": "10.51.180.1", "ten1_0_2_uplink_switch_port": "Te1/0/2", "data_interface_range": "gi1/0/1-48,gi2/0/7-42", "hostname": "Placeholder-216", "ten1_0_1_uplink_switch_port": "Te1/0/1", "ip_name_server": "10.5.180.29", "snmp_server_location": "Placeholder - MDF 216 - Library Back Room"}'
```

**Comment by PackeTsar** [comment]
For a complex keystore value, your merging values should look multi-layered as below.

```
2019-03-07 14:37:49:   cfact.get_keystore_id: Checking Keystores and IDArrays for (SERIAL100)

2019-03-07 14:37:49:   cfact.get_keystore_id: ID (SERIAL100) resolved directly to a keystore

2019-03-07 14:37:49:   cfact.get_template: Looking up association for identity (SERIAL100)

2019-03-07 14:37:49:   cfact.get_template: Found associated template (SHORT_TEMPLATE)

2019-03-07 14:37:49:   cfact.get_template: Template (SHORT_TEMPLATE) exists in local config. Returning

2019-03-07 14:37:49:   cfact.merge_final_config: Merging with values:
{
    "vl1_ip_address": "10.0.0.201", 
    "hostname": "SOMEDEVICE", 
    "settings": {
        "mgmt_ip_mask": "255.255.252.0", 
        "wireless_interface_range": "gi2/0/1-6,gi2/0/43-48", 
        "mgmt_ip": "10.51.183.216", 
        "default_gateway": "10.51.180.1", 
        "ten1_0_2_uplink_switch_port": "Te1/0/2", 
        "data_interface_range": "gi1/0/1-48,gi2/0/7-42", 
        "hostname": "Placeholder-216", 
        "ten1_0_1_uplink_switch_port": "Te1/0/1", 
        "ip_name_server": "10.5.180.29", 
        "snmp_server_location": "Placeholder - MDF 216 - Library Back Room"
    }
}
```

**Comment by marcabomb** [comment]
Thank you John for your help and for this great project. I had originally started off using the external CSV file but had the same issue. So I used the ztp request external-keystore-test command, then pasted those commands in manually, and then removed the original external keystore statements. My original keystore command had the quotes around each key value pair but for some reason they don't when doing a ztp show run.

**Here is an output from history buffer on the host I am running freeZTP from.**
  648  ztp request external-keystore-test PLACEHOLDERTEST
  649  ztp set keystore PLACEHOLDER-216 keystore_id PLACEHOLDER-216
  650  ztp set keystore PLACEHOLDER-216 settings {"hostname": "PLACEHOLDER-216", "ip_name_server": "10.5.180.29", "wireless_interface_range": "gi2/0/1-6,gi2/0/43-48","data_interface_range": "gi1/0/1-48,gi2/0/7-42","ten1_0_1_uplink_switch_port": "Te1/0/1","ten1_0_2_uplink_switch_port": "Te1/0/2", "mgmt_ip": "10.51.183.216", "mgmt_ip_mask": "255.255.252.0", "default_gateway": "10.51.180.1", "snmp_server_location": "PLACEHOLDER – MDF 216 – Library Back Room"}

For some reason using flat values inside of the CSV didn't occur to me so I may do that. I know I will need nested values in the future though so I started off with the complex values.

**Comment by derek-shnosh** [comment]
@marcabomb, I used a CSV as @PackeTsar suggested, but then stored a bunch of static and dynamic variables in the template so we didn't have to be concerned with mucking things up when modifying the CSV to add stacks or serials... it also kept the FreeZTP configuration concise and easy to validate.

Your issue prompted me to finish a blog post I've had sitting in _drafts_ for a while now, it might help shed some light on how you might leverage the template for some of what you're trying to accomplish.

**Full details here: https://www.shnosh.net/jinja2-templating-freeztp/**

### Example

To build a list of interfaces based on how many switches are found in the stack...

#### ZTP Config

```bash
ztp set external-keystore SBS type csv
ztp set external-keystore SBS file '/srv/ztp/keystore/ks_asw.csv'
#
ztp set external-template SBS file '/srv/ztp/template/tmpl_asw.j2'
```

#### CSV (ks_asw.csv)

```csv
keystore_id,association,idarray_1,idarray_2,idarray_3,idarray_4
ASW-TR04-02,ASW,FOC11111111,FOC22222222,FOC33333333,FOC44444444
```

#### Template (tmpl_asw.j2)

> Lines that begin with `!` will appear in the merged config, but will be ignored by the switch.

```jinja2
!---- IDARRAY         > {{idarray|default("N/A")}} 
{%set gi_ints,te_ints=[],[]-%}
{%for sw in idarray-%}
{%  set i=loop.index-%}
{%  set gi_ints,te_ints=
        gi_ints.append("Gi%s/0/1-36"|format(i)),
        te_ints.append("Te%s/0/37-47"|format(i))-%}
{%endfor-%}
!---- GI_INTS         > {%set gi_ints=gi_ints|join(",")-%} {{gi_ints}}
!---- TE_INTS         > {%set te_ints=te_ints|join(",")-%} {{te_ints}}
...
```

##### What's happening...

- `{{idarray|default("N/A")}}` will print the `idarray` dict, which is a list of all switch serial numbers passed from FreeZTP. _If no serials were parsed from the keystore, it will print "N/A"._
- `{%set gi_ints,te_ints=[],[]-%}` creates empty dicts for `gi_ints` and `te_ints`.
  > I was working with C3850-12X48U's with mGig interfaces; i.e. interfaces 1-36 are configured as `GigabitEthernet` and 37-48 are configured as `TenGigabitEthernet`... I wish the IOS BU would get on board with the generic `Ethernet` naming convention.
- `{%for sw in idarray-%}` → `{%endfor-%}` is a _for loop_ that appends an interface range to each dict for every switch in the stack.
   - The example provided has 4 switches in `idarray`, so it would end up with 4 interface ranges...

     | Switch Count | `gi_ints` |
     | :-: | :- |
     |  1  | `gi1/0/1-36` |
     |  2  | `gi1/0/1-36,gi2/0/1-36` |
     |  3  | `gi1/0/1-36,gi2/0/1-36,gi3/0/1-36` |
     |  **4**  | **`gi1/0/1-36,gi2/0/1-36,gi3/0/1-36,gi4/0/1-36`** |

**Comment by marcabomb** [comment]
> @marcabomb, I used a CSV as @PackeTsar suggested, but then stored a bunch of static and dynamic variables in the template so we didn't have to be concerned with mucking things up when modifying the CSV to add stacks or serials... it also kept the FreeZTP configuration concise and easy to validate.
> 
> Your issue prompted me to finish a blog post I've had sitting in _drafts_ for a while now, it might help shed some light on how you might leverage the template for some of what you're trying to accomplish.
> 
> **Full details here: https://www.shnosh.net/jinja2-templating-freeztp/**
> 
> ### Example
> To build a list of interfaces based on how many switches are found in the stack...
> 
> #### ZTP Config
> ```shell
> ztp set external-keystore SBS type csv
> ztp set external-keystore SBS file '/srv/ztp/keystore/ks_asw.csv'
> #
> ztp set external-template SBS file '/srv/ztp/template/tmpl_asw.j2'
> ```
> 
> #### CSV (ks_asw.csv)
> ```
> keystore_id,association,idarray_1,idarray_2,idarray_3,idarray_4
> ASW-TR04-02,ASW,FOC11111111,FOC22222222,FOC33333333,FOC44444444
> ```
> #### Template (tmpl_asw.j2)
> > Lines that begin with `!` will appear in the merged config, but will be ignored by the switch.
> 
> ```jinja2
> !---- IDARRAY         > {{idarray|default("N/A")}} 
> {%set gi_ints,te_ints=[],[]-%}
> {%for sw in idarray-%}
> {%  set i=loop.index-%}
> {%  set gi_ints,te_ints=
>         gi_ints.append("Gi%s/0/1-36"|format(i)),
>         te_ints.append("Te%s/0/37-47"|format(i))-%}
> {%endfor-%}
> !---- GI_INTS         > {%set gi_ints=gi_ints|join(",")-%} {{gi_ints}}
> !---- TE_INTS         > {%set te_ints=te_ints|join(",")-%} {{te_ints}}
> ...
> ```
> 
> ##### What's happening...
> * `{{idarray|default("N/A")}}` will print the `idarray` dict, which is a list of all switch serial numbers passed from FreeZTP. _If no serials were parsed from the keystore, it will print "N/A"._
> * `{%set gi_ints,te_ints=[],[]-%}` creates empty dicts for `gi_ints` and `te_ints`.
>   > I was working with C3850-12X48U's with mGig interfaces; i.e. interfaces 1-36 are configured as `GigabitEthernet` and 37-48 are configured as `TenGigabitEthernet`... I wish the IOS BU would get on board with the generic `Ethernet` naming convention.
> * `{%for sw in idarray-%}` → `{%endfor-%}` is a _for loop_ that appends an interface range to each dict for every switch in the stack.
>   
>   * The example provided has 4 switches in `idarray`, so it would end up with 4 interface ranges...
>     
>     
>     
>     Switch Count
>     `gi_ints`
>     
>     
>     
>     
>     1
>     `gi1/0/1-36`
>     
>     
>     2
>     `gi1/0/1-36,gi2/0/1-36`
>     
>     
>     3
>     `gi1/0/1-36,gi2/0/1-36,gi3/0/1-36`
>     
>     
>     **4**
>     **`gi1/0/1-36,gi2/0/1-36,gi3/0/1-36,gi4/0/1-36`**

Thank you @derek-shnosh this is helpful.

**Comment by PackeTsar** [comment]
Closing this as it seems the issue was resolved.
