### ISSUE TITLE
Update 2960 firmware with bin

### ISSUE THREAD

**Issue by craigw76** [convergeone/freeztp#42]
I've not been able to find anything on this. I have a bunch of new 2960s I need to upgrade the firmware on. I downloaded the latest version from Cisco today.  (I've tried older versions as well). The switch connects to the TFTP server and seems to successfully download the image file, then complains because it is not an archive. The procedure seems to work fine with the tar file. The switch appears to download the file from the TFTP server twice. Watching ztp show downloads live, The percentage goes to 100 twice on the same line. No updates on the serial console until it's completed the second download.

Here's the output on the console when using a .bin file.
`
Loading freeztp_ios_upgrade from 192.168.0.2 (via Vlan1): !
[OK - 33 bytes]
 got vend id vend spec. info ret: succeed
Mar 27 21:53:18.196: AUTOINSTALL: Obtain tftp server address (opt 150) 192.168.0.2
examining image...
%Tar checksum error in tftp://192.168.0.2/c2960x-universalk9-mz.152-7.E.bin
%Error opening flash:update/info (No such file or directory)
ERROR: Image is not a valid IOS image archive.
Loading network-confg from 192.168.0.2 (via Vlan1): !
[OK - 65 bytes]

Mar 27 21:56:51.658: AUTOINSTALL: Error (1) Image is not a valid IOS image archive or not existing
`

Is there something else that must be set when using a .bin vs .tar? 

Thanks,
Craig

**Comment by PackeTsar** [comment]
Autoinstall on the 2960 will not upgrade using the BIN. It requires you provide the TAR file.

**Comment by craigw76** [comment]
OK. Thanks. I'd not found that info anywhere. Makes sense why it did not work.

**Comment by derek-shnosh** [comment]
@craigw76 You may be able to disable the image-discovery option and use an applet to fetch and install the upgrade; check the [usage tips section of this repo](https://github.com/PackeTsar/freeztp/blob/latest/TIPS.md#use-case-upgrade-ios-xe-37x-to-1636).
