### ISSUE TITLE
WS-C3560CPD-8PT with 12.2(55)EX2 breaks freeZTP

### ISSUE THREAD

**Issue by ascii-ts** [convergeone/freeztp#44]
when installing a WS-C3560CPD-8PT with it's default image 12.2(55)EX2 freeZTP crashs on snmp discover/config creation.
It looks like the TFTP server fails once the switch requests its ZTP-23XYZ config.

When i upgrade the software first to a 15IOS image the install works fine.

**Comment by derek-shnosh** [comment]
Without any configs or logs, its hard to determine a root-cause... Are you able to provide these? To make it easier (less data to sift through), it may be beneficial to clear the log and make an attempt, then grab the logs.

**Comment by ascii-ts** [comment]
i will try to get same next week.
my college is on vacation.

basicly ztp stopped working once the tftp request was send/recieved.
i attachet parts of the syslog. maybe that helps
[ztp-3560cpd-8pt-log.txt](https://github.com/PackeTsar/freeztp/files/3137432/ztp-3560cpd-8pt-log.txt)

after the software update on the switch the same template and keystrokes work

**Comment by PackeTsar** [comment]
Seems like it threw i J2 handling exception. The L2 handing has been rewritten in v1.2.0. Upgrade to that and open a new issue if it happens again.
