### ISSUE TITLE
some issues after OS update

### ISSUE THREAD

**Issue by duewydo** [convergeone/freeztp#47]
I reluctantly headed a request to update Ubuntu 18.04 on the ztp server and after the upgrade and reload, while the ZTP config seemed fine it was only sending out the short template. I reconfigured my external keystore in the ztp config and it seems to be working fine but show ztp provisioning doesn't show any new entries. show ztp download is working, show logging show everything looks to be working, it is just that the provisioning log isn't updating. 

Any ideas to fix the provision log?

**Comment by PackeTsar** [comment]
So are templates being properly merged and downloaded by switches?

**Comment by duewydo** [comment]
at first they were not, but then I re ran the external keystore config and it is working. I provisioned a switch this morning successfully but it didn't show up in the provision log.

**Comment by duewydo** [comment]
I re-installed ztp ontop of itself and then I noted that new provisions are showing up in ztp show provisioning it is just that it is no longer sorted by time. I cannot honestly tell how it is being sorted. How would I clear the provisioning log?

**Comment by PackeTsar** [comment]
So they are not sorted by time currently. I have received this feedback from a few places. Adding it to the bug list to be fixed.

**Comment by PackeTsar** [comment]
You can clear the provisioning log with `ztp clear provisioning`

**Comment by duewydo** [comment]
derp, I should have been able to figure that out on my own. Please close out this issue.

Thank you!

**Comment by PackeTsar** [comment]
Closing
