### ISSUE TITLE
Amazing Work!

### ISSUE THREAD

**Issue by dalwar23** [convergeone/freeztp#51]
I am really amazed by the depth of the ZTP script you have created. I am creating this issue just to say `thank you`. It's really fantastic what you have done. 👏 👏 

I am going to try this out. 🙇 

Have you considered modulating the package into multiple files and creating a "pip" package?

**Comment by PackeTsar** [comment]
Thank you!

Yes I have thought to do that. If I ever do a 2.0 version, I will likely refactor most if not all of it into cleaner and more maintainable modules. Not sure if I would use PIP or regular Linux package managers for install/upgrades though.

I was very unfamiliar with better coding practices when I originally wrote FreeZTP, and I'd like to put those better practices to use if/when I ever do a rewrite.
