### ISSUE TITLE
 Post Install Script

### ISSUE THREAD

**Issue by helpdeskdan** [convergeone/freeztp#53]
With vstack being axed, I'm looking into freeztp as a possible replacement.  However, I don't see any way to implement a "Post Install Script" (apologies if I'm missing something)  How do you set things such as vtp?

**Comment by EarlRamirez** [comment]
@helpdeskdan for what it's worth I use EEM to do a few post work and then put ansible to work and it has been working well.

**Comment by helpdeskdan** [comment]
Clever - post your ansible scripts!  I have used ciscocmd (lazy) to do similar.  Until recently, I would send a carefully crafted vstack packet to write a startup, upgrade ios, and do post install.  Worked very well, till Cisco abandoned it.  Another option might be TCL.

**Comment by derek-shnosh** [comment]
@helpdeskdan and @EarlRamirez, you may be able to modify my [(Free)ZTP-Watcher](https://github.com/derek-shnosh/ztp-watcher) script to perform post-provisioning tasks.

I wrote it to get around the limitation for 2960 switches that requires the ZTP upgrade to use a **.tar** file. In its current form, it copies the **.bin** image via TFTP, sets the boot variable and then writes the config. It is triggered by FreeZTP's custom log file option.

**Comment by helpdeskdan** [comment]
Netmiko - I can work with that, thank you Derek.  Though, I'd also love to see Earl's EMM script.  SmartInstall would work well, but it's deprecated so I won't bother sharing my code to generate those packets.  I'm a little surprised that this functionality is not in FreeZTP - nobody changes sdm profiles or vtp mode?  

Of note to these projects: Cisco removed SmartInstall without warning - not even in the release notes.  (This functionality competes with DNA)  I can't help but wonder if the same fate is in store for DHCP options, tftp of network-confg or EMM.

**Comment by PackeTsar** [comment]
Hey @helpdeskdan. I have been wondering the same thing about Autoinstall being removed. I supposed we will find out, then I will HAVE to extend FreeZTP to use the new PNP function (if it is possible).

In regards to running an external script after a provisioning action, I have been considering adding a FreeZTP feature to allow you to craft and run a BASH command or pull in and execute an external python script after a configured delay from a provisioning action. Would this do what you are wanting? It might also possibly solve @derek-shnosh's issue where he needed a watcher.

**Comment by derek-shnosh** [comment]
@helpdeskdan - there a couple EEM script examples in the [usage tips](https://github.com/PackeTsar/freeztp/blob/latest/TIPS.md) that might get the ball rolling for you as well.

`vtp mode transparent` (the _right_ way to configure VTP 😉) can be configured in the switch template.

**Comment by helpdeskdan** [comment]
I only found [one reference to July 2018](https://community.cisco.com/t5/switching/vstack-basic-not-working-on-a-2960x/td-p/3797785) on the net.  And with that, my solution was down the tubes.  I'll not waste your time with vehement condemnations of Cisco. 

Derek simply wants his ios faster, so he increases the tftp blocksize and then scripts the bin.  If you don't use macros or whatnot, this would vastly cut down deployment time.  (though, I may have opted for ftp instead of tftp)  His use case is similar, but not mine. 

Smart Install had a good option to do these things [as you can see here](https://www.cisco.com/c/en/us/td/docs/switches/lan/smart_install/configuration/guide/smart_install/tasks.html#pgfId-1104039) 

As I recall, you can end up with vlans in the config that didn't actually exist when you did 'show vlan' on the switch.  This would necessitate the post script to be modified per switch, right?  Your solutions are more elegant than mine,  hence I toss the matter out for discussion.

**Comment by helpdeskdan** [comment]
I had though EMM was only for IOS-XE, but that appears not to be the case - I will read more, thanks.

**Comment by EarlRamirez** [comment]
@helpdeskdan the EEM script I use basically generate the RSA key and save the config, below is how I use ZTP with ansible
- Have a base template, this is used for a group similar switches 
- Use an external keystore for unique values, for example, hostname, IP address, etc.
- Use ansible playbooks for any additional tweaking

**Comment by helpdeskdan** [comment]
Apologies are in order.  My method has always been, via crafted vtstack packets, to copy to start.  Forever drilled in my head was this idea: VTP/Vlan/SDM can NOT be configured via tftp.  Never in my imagination did it it occur to me that copying to RUN, in fact, eliminates these limitations!  I am thus found guilty of wasting these good gentlemen's time, for which I beg their pardon.

Through my folly, I have been introduced to ZTP-Watcher and EMM.  Some cobbling to ZTP-Watcher, with an snmp call here and a dictionary there, and I can probably use it to send a different IOS based on switch model.  (A much needed feature that I see no way to add to FreeZTP)  I don't quite understand EMM, but will definitely look into it.  I urge Earl to post a more detailed "how to" on his method, and thank all you gentlemen for your time.

**Comment by EarlRamirez** [comment]
@helpdeskdan I will put something together during the weekend that should get you started. No apologies are needed.
