### ISSUE TITLE
Ubuntu 19 dependencies

### ISSUE THREAD

**Issue by helpdeskdan** [convergeone/freeztp#54]
Couple quick notes on install:

>Reading state information... Done

>E: Unable to locate package gmp
>E: Unable to locate package python-devel

You want perhaps libgmp3-dev python-dev?

>E: Unable to locate package epel-release

Um.... Ubuntu, not Cent?

**Comment by EarlRamirez** [comment]
> Couple quick notes on install:
> 
> > Reading state information... Done
> 
> > E: Unable to locate package gmp
> > E: Unable to locate package python-devel
> 
> >You want perhaps libgmp3-dev python-dev?

 Some distributions tend to rename their packages with a major release, so the packages can change. 

> > E: Unable to locate package epel-release
> >This is CentOS
> Um.... Ubuntu, not Cent?

I have only used CentOS for freeZTP, you can either try Ubuntu 16 or CentOS 7 for the time being.

**Comment by helpdeskdan** [comment]
Works for Ubuntu 19, suggest those minor tweaks for package name, could perhaps check /ect/issue for ver & adjust accordingly.  Thanks.

**Comment by EarlRamirez** [comment]
Glad to hear that it works
