### ISSUE TITLE
ztp over port-channel

### ISSUE THREAD

**Issue by pijav** [convergeone/freeztp#57]
Hey!

First of all I am really happy to use FreeZTP. Have some succesfull installations for 2960 and 3850
I was just wondering is there any way to provision 9300 switch over port-channel configured as trunk? 

SW9300 
   |  |               <-  this is trunk
CORE

vLan for provisioning - 100
Management vlan - 150

I tried this interface configuration on the CORE switch:
**interface Port-channel25**
 _description NET-DNL SW9300
 switchport
 switchport trunk native vlan 100
 switchport mode dynamic desirable
 switchport trunk allowed vlan 150,100
 spanning-tree bpduguard enable_

**interface TenGigabitEthernet1/1/10**
 _description NET-DNL SW9300, Te1/0/7
 switchport
 switchport trunk native vlan 100
 switchport mode dynamic desirable
 channel-group 25 mode active_

The port is going err-disable state. I think I am missing the point.

Anyway I will be grateful for any advice regarding FreeZTP+Port-channel

Cheers!

**Comment by PackeTsar** [comment]
Yes I have been doing this by allowing the port-channel to put the links in individual mode when no LACP is detected. You can use the command `no port-channel standalone-disable` to do this.
