### ISSUE TITLE
Fatal: unable to access https://github.com/packetsar/freeztp.git

### ISSUE THREAD

**Issue by tristaneniyan** [convergeone/freeztp#58]
when I was running in Ubuntu server 18.04lts this is the error we are getting. I have searched this in here in issues i didn't find this issue so I am posting it. kindly look into it and respond.

Thanks

**Comment by PackeTsar** [comment]
Can you post the error?

**Comment by PackeTsar** [comment]
Oh i see, it is the title. Looks like it is some kind of internet access issue where your Git client can't get to the internet.

**Comment by tristaneniyan** [comment]
![image](https://user-images.githubusercontent.com/22721519/70801651-710ae380-1dd5-11ea-87ff-bb0a3a3601e3.png)

**Comment by PackeTsar** [comment]
Are you doing some kind of SSL decryption on a firewall?

**Comment by tristaneniyan** [comment]
yeah the firewall is on i'll try disabling it and try now and report it soon.

**Comment by tristaneniyan** [comment]
No luck mate. here it is again i stuck up with the same place
![image](https://user-images.githubusercontent.com/22721519/70801849-fa221a80-1dd5-11ea-9f0d-62005274e313.png)

**Comment by PackeTsar** [comment]
Try using `git -c http.sslVerify=false clone ...`

**Comment by tristaneniyan** [comment]
wow, thanks man appreciate it much thanks. 
![image](https://user-images.githubusercontent.com/22721519/70802835-8e8d7c80-1dd8-11ea-9287-452b988c5c5e.png)

**Comment by PackeTsar** [comment]
No problem!
