### ISSUE TITLE
regarding installing ztp.py

### ISSUE THREAD

**Issue by tristaneniyan** [convergeone/freeztp#60]
![image](https://user-images.githubusercontent.com/22721519/70970288-f89d6e80-20c3-11ea-8fc3-917410b30821.png)

when installing ztp.py for the following packages i am getting these errors(see image).
packages:
1.pysnmp
2.requests
3.req_toolbelt
4.jinja2
5.netaddr
6.netifaces
7.isc dhcp leases

     So, i tried installing separately these packages still i am getting these errors again and again

**Comment by PackeTsar** [comment]
Check out issue #58 

Seems like they had a similar problem.
