### ISSUE TITLE
Unable to install on Oracle Linux Server 7.7

### ISSUE THREAD

**Issue by machine718** [convergeone/freeztp#65]
I get the following message when I try to install on my Oracle Linux Server 7.7

Unsupported OS Type! PLease create an issue at https://github.com/PackeTsar/freeztp/issues/ and include below information
('Oracle Linux Server', '7.7' ' ')

**Comment by machine718** [comment]
In addition my server is a RedHat Enterprise Linux Server Release 7.7 (Maipo)

**Comment by PackeTsar** [comment]
This is a pretty niche use case. Are you able to deploy it on one of the supported platforms (CentOS, Ubuntu/Debian)?
