### ISSUE TITLE
License.

### ISSUE THREAD

**Issue by nathantabailey** [convergeone/freeztp#71]
Can you please add a license to the project?

**Comment by nathantabailey** [comment]
Following up with a little explanation. 

We'd love to contribute to this project and are planning to use it internally, but unfortunately we require a license to be present to guarantee we are allowed to use this code. Here are a few licenses which would allow us to use this code, GPLv3, MIT, Apache License. 

More info here: https://resources.whitesourcesoftware.com/blog-whitesource/open-source-licenses-explained
Thanks!

Nathan

**Comment by PackeTsar** [comment]
Hey Nathan. Sorry this took so long. A GNU license has been added.

**Comment by nathantabailey** [comment]
Thank you sir.  I appreciate you.  This is a great project.
