### ISSUE TITLE
Prerequisite spec for devices to works with freeztp

### ISSUE THREAD

**Issue by chenoi** [convergeone/freeztp#79]
HI, I would like to know what is the requirement or condition for devices to met with freeztp? I'm using multi type whitebox that have snmp, does it fit the requirement? Pls advise further. Thank you

**Comment by pschapman** [comment]
Hi -
If your device conforms to the ladder diagram shown in the [readme](https://github.com/PackeTsar/freeztp#ztp-process), then ZTP will be compatible.

1. Switch must be able to discover ZTP server using DHCP option 150 (TFTP Server)
2. Switch must then query TFTP for a generic config
3. Switch must then query TFTP for a specific config based on host name

PSC
