### ISSUE TITLE
AttributeError: 'module' object has no attribute 'TftpContextServer'

### ISSUE THREAD

**Issue by kbarton1212** [convergeone/freeztp#80]
Hi,

I am running Linux Ubuntu 18.04.5 LTS on a VM as a new install. I am not able to start the ZTP service due to the following errors:

-- The start-up result is RESULT.
Mar 09 09:52:16 ZeroTouchLab sudo[1490]: pam_unix(sudo:session): session closed for user root
Mar 09 09:52:16 ZeroTouchLab sudo[1496]:     root : TTY=pts/0 ; PWD=/root ; USER=root ; COMMAND=/bin/systemctl status z
Mar 09 09:52:16 ZeroTouchLab sudo[1496]: pam_unix(sudo:session): session opened for user root by root(uid=0)
Mar 09 09:52:16 ZeroTouchLab sudo[1496]: pam_unix(sudo:session): session closed for user root
Mar 09 09:52:16 ZeroTouchLab bash[1493]: 2021-03-09 09:52:16:   integration_main._load: Beginning load of integration o
Mar 09 09:52:16 ZeroTouchLab bash[1493]: 2021-03-09 09:52:16:   interpreter: Command to run received. Calling start_tft
Mar 09 09:52:16 ZeroTouchLab bash[1493]: Traceback (most recent call last):
Mar 09 09:52:16 ZeroTouchLab bash[1493]:   File "ztp", line 4093, in <module>
Mar 09 09:52:16 ZeroTouchLab bash[1493]:     interpreter()
Mar 09 09:52:16 ZeroTouchLab bash[1493]:   File "ztp", line 3558, in interpreter
Mar 09 09:52:16 ZeroTouchLab bash[1493]:     start_tftp()
Mar 09 09:52:16 ZeroTouchLab bash[1493]:   File "ztp", line 3501, in start_tftp
Mar 09 09:52:16 ZeroTouchLab bash[1493]:     tftpy.TftpContextServer.start = start  # Overwrite the function
Mar 09 09:52:16 ZeroTouchLab bash[1493]: AttributeError: 'module' object has no attribute 'TftpContextServer'
Mar 09 09:52:16 ZeroTouchLab systemd[1]: ztp.service: Main process exited, code=exited, status=1/FAILURE
Mar 09 09:52:16 ZeroTouchLab systemd[1]: ztp.service: Failed with result 'exit-code'.

I have tried rebooting, as well as updating/upgrading and installing python-tftpy. I also tried searching to see if anyone else had a similar issue, but was not able to find anything.

**Comment by PackeTsar** [comment]
You don't need to install tftpy, the installer installs a specific version of it for you.

**Comment by kbarton1212** [comment]
The reason why I mentioned installing tftpy is because prior to this, the ztp service wasn't starting due to "ImportError: No module named tftpy". So I looked through closed issues and saw someone posted installing python-tftpy.

**Comment by PackeTsar** [comment]
OK. My guess is that you didn't have PIP installed before running the installer. Try following the Ubuntu20 instructions in the README.

**Comment by kbarton1212** [comment]
Thanks, that did it. In case it's also worth mentioning in the README for Ubunut 18, I wasn't able to install "sudo apt install python2" as I was getting "E: Unable to locate package python2". I ended up running sudo apt-get install python-pip and then followed the rest of the Ubuntu 20 instructions and it worked.

https://stackoverflow.com/questions/66287658/ubuntu-18-04-sudo-apt-get-install-python2-results-in-e-unable-to-locate-pack

**Comment by PackeTsar** [comment]
I updated the README with that info
