### ISSUE TITLE
How is option 125 encoded in freeztip

### ISSUE THREAD

**Issue by Pavel077** [convergeone/freeztp#84]
Hello.

First of all, thank you very much for your excellent software!

Could you please explain how is filename "freeztp_ios_upgrade" encoded into this hex string in dhcpd config?
send imagediscoveryfile-option 00:00:00:09:**0A**:05:13:66:72:65:65:7A:74:70:5F:69:6F:73:5F:75:70:67:72:61:64:65;

The byte in question is the fifth one, with value 0A.

I understand that:
first four bytes 00-00-00-09 are  "Enterprise Number (Cisco Value)"
6th byte is always 05 (Cisco’s auto-update sub-option)
7th byte is 13 because it is the length of "freeztp_ios_upgrade" string in bytes  19 decimal = 13 hex
But from what I've read the 5th byte should contain length **of all following fields**, so in our case it should be 15 hex, not 0A?

Nevertheless, cisco switch is requesting freeztp_ios_upgrade file, so I guess there is no error in encoding. 

Once again, thank you :)

**Comment by PackeTsar** [comment]
Have a look at the [calcopt125hex function](https://github.com/PackeTsar/freeztp/blob/latest/ztp.py#L1356). It looks like those bytes in question are just hardcoded

**Comment by Pavel077** [comment]
Thank you.

It appears catalyst (at least 2960x) is ignoring this value, because i've tried manually encoding string `c2960_firmware` instead of `freeztp_ios_upgrade` and I put actual length (0x10) of option 125 into `5th` byte, as described in [cisco manual](https://www.cisco.com/c/en/us/support/docs/smb/switches/cisco-small-business-200-series-smart-switches/smb5328-configure-option-125-on-a-server-to-allow-dynamic-host-confi.html)

`send imagediscoveryfile-option 00:00:00:09:10:05:0e:63:32:39:36:30:5f:66:69:72:6d:77:61:72:65`

And catalyst succesfully downloaded `c2960_firmware` file from tftp.
