### ISSUE TITLE
Very slow TFTP transfer

### ISSUE THREAD

**Issue by austind** [convergeone/freeztp#91]
Last several deployments of C9200/9300 devices have pegged TFTP to ~200Kbps, as shown by `ztp show downloads`.

Reloading the switch causes it to skip image upgrade & get config as expected.

Then I issue:
```
ip tftp source-interface g0/0
install add file tftp://192.168.1.1/cat9k_iosxe.17.03.03.SPA.bin activate commit
```

then `ztp show downloads` shows this transfer goes at 300Mbps+

Using freeztp 1.5.1

thoughts?

**Comment by PackeTsar** [comment]
I recommend using EEM to perform your OS upgrade. The built in image upgrade function has never seemed to work well due to how Autoinstall tries to perform it. Check out the [Usage Tips](https://github.com/PackeTsar/freeztp/blob/latest/TIPS.md) page to see examples on how to do this.

**Comment by brokoler** [comment]
I also tested FreeZTP's tftp server and compared the transfer speed via `copy tftp:imagefile.bin flash:` to my TFTPD64 server on Windows. The test was done with a fully configured switch after the Auto-Install process. Increasing the blocksize made it worse with FreeZTP's tftp, resulting in more pauses. With my Windows tftp server the blocksize increased the copying time a lot. FreeZTP had many pauses during copying, which wasn't the case with TFTPD64. 

FreeZTP: over 60 minutes with blocksize 8192 and many pauses. Transfer looked like: `!!!.........!!........!.....!!!......!!`
TFTPD64: 8 minutes with blocksize 8192. Transfer looked like: `!!!!!!!!!!!!!!!!!!!!!!!`

I verified the issue and see following with `ztp show downloads`
![image](https://user-images.githubusercontent.com/57031979/137566248-05071d9a-0ad6-4f9a-8d44-800821e92083.png)

@PackeTsar Could there be an issue with pyftp in the recent version? It would be interesting if we could set an external tftp server only for image upgrades.

Tested with C3650-48TS-E

**Comment by pschapman** [comment]
Hi @eggplanting -

I find that TFTP is fairly unreliable and extremely slow for any of the IOS-XE platforms.  TCP protocols tend to have significantly better results.  As suggested by @PackeTsar, you should check out the EEM examples.  I typically recommend adding Apache to the base ZTP server and pulling down updates via HTTP.

PSC

**Comment by brokoler** [comment]
Hi @pschapman

indeed, I'm getting started with EEM scripting right now. Even transfering via TFTP is now much faster, since I can point to an external server.

The example scripts are a big help.
