### ISSUE TITLE
Can I disable imagediscoveryfile?

### ISSUE THREAD

**Issue by danny-fosterman** [convergeone/freeztp#95]
Is it possible to disable the software upgrade in the beginning of the ztp process? I looked around but couldn't find it. I don't plan on using the feature in freeztp, also I'm getting an error and the ztp process doesn't get into the initial template. It could be because I didn't upload an image to the tftp server. Any ideas? I searched around but couldn't find out how.

SCRPT_PREAMBLE_NOT_MATCHED Script file format invalid: tftp://10.10.10.77/freeztp_io
s_upgrade
*May 13 00:06:25.698: %PARSER-4-BADCFG: Unexpected end of configuration file.

**Comment by PackeTsar** [comment]
Yes you can. Most certain way is to disable it in the DHCP scope with `ztp set dhcpd SCOPENAME imagediscoveryfile-option disable`

**Comment by danny-fosterman** [comment]
I'm not using the built in dhcp server will that still work?

**Comment by PackeTsar** [comment]
If you're using an external DHCP server, then just remove the DHCP option which points to the upgrade file.

**Comment by danny-fosterman** [comment]
Thanks for taking the time to answer my questions!

**Comment by PackeTsar** [comment]
You bet!
